export const candidates = [
  {
    id: "1",
    name: "Ana García Martínez",
    email: "ana.garcia@techinnovate.com",
    position: "Desarrollador Frontend Senior",
    stage: "Primera Entrevista Individual",
    interviewDate: new Date("2023-06-05T10:00:00"),
    avatar: "https://i.pravatar.cc/150?img=1",
    experience: "5 años",
    skills: ["React", "TypeScript", "NextJS", "TailwindCSS"],
  },
  {
    id: "2",
    name: "Carlos Rodríguez López",
    email: "carlos.rodriguez@uxmastery.com",
    position: "Diseñador UX/UI",
    stage: "Segunda Entrevista",
    interviewDate: new Date("2023-06-12T14:00:00"),
    avatar: "https://i.pravatar.cc/150?img=2",
    experience: "4 años",
    skills: ["Figma", "Adobe XD", "Sketch", "User Research"],
  },
  {
    id: "3",
    name: "María López Sánchez",
    email: "maria.lopez@projectpro.com",
    position: "Gerente de Proyecto Senior",
    stage: "Segunda Entrevista",
    interviewDate: new Date("2023-06-19T11:00:00"),
    avatar: "https://i.pravatar.cc/150?img=3",
    experience: "8 años",
    skills: ["Agile", "Scrum", "Jira", "Gestión de equipos"],
  },
  {
    id: "4",
    name: "Juan Pérez González",
    email: "juan.perez@backendwizard.com",
    position: "Desarrollador Backend",
    stage: "Reclutados",
    interviewDate: new Date("2023-06-26T15:00:00"),
    avatar: "https://i.pravatar.cc/150?img=4",
    experience: "3 años",
    skills: ["Node.js", "Express", "MongoDB", "GraphQL"],
  },
  {
    id: "5",
    name: "Laura Martínez Fernández",
    email: "laura.martinez@datainsights.com",
    position: "Analista de Datos Senior",
    stage: "Reclutados",
    interviewDate: new Date("2023-07-03T13:00:00"),
    avatar: "https://i.pravatar.cc/150?img=5",
    experience: "6 años",
    skills: ["Python", "R", "SQL", "Tableau"],
  },
];
