import nodemailer from "nodemailer";

export const SendEmail = async (list) => {
  const transporter = nodemailer.createTransport({
    service: "gmail",
    host: "smtp.gmail.com",
    port: 465,
    secure: true,
    auth: {
      user: "carlos.facundo.rr@gmail.com",
      pass: process.env.EMAIL_PASS,
    },
  });

  const mailOption = {
    from: {
      name: "Carlos RR",
      address: "carlos.facundo.rr@gmail.com",
    },
    to: list,
    // to: email,
    subject: "Mensaje de Marketing",
    html: `
   <!DOCTYPE html><html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en"><head><title></title><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]--><style>
*{box-sizing:border-box}body{margin:0;padding:0}a[x-apple-data-detectors]{color:inherit!important;text-decoration:inherit!important}#MessageViewBody a{color:inherit;text-decoration:none}p{line-height:inherit}.desktop_hide,.desktop_hide table{mso-hide:all;display:none;max-height:0;overflow:hidden}.image_block img+div{display:none}sub,sup{line-height:0;font-size:75%} @media (max-width:620px){.social_block.desktop_hide .social-table{display:inline-block!important}.mobile_hide{display:none}.row-content{width:100%!important}.stack .column{width:100%;display:block}.mobile_hide{min-height:0;max-height:0;max-width:0;overflow:hidden;font-size:0}.desktop_hide,.desktop_hide table{display:table!important;max-height:none!important}}
</style><!--[if mso ]><style>sup, sub { font-size: 100% !important; } sup { mso-text-raise:10% } sub { mso-text-raise:-10% }</style> <![endif]--></head><body class="body" style="background-color:#2b2e31;margin:0;padding:0;-webkit-text-size-adjust:none;text-size-adjust:none"><table class="nl-container" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#2b2e31"><tbody><tr><td><table class="row row-1" 
align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;color:#333;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="50%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%"><div class="alignment" align="left" style="line-height:10px"><div style="max-width:200px"><img 
src="https://easymailing-prod-bee.s3.amazonaws.com/images/remax_noa_easymailing_com/editor_images/43ebbe61-392d-468a-a59f-aef81612c77e.png" style="display:block;height:auto;border:0;width:100%" width="200" alt="Image" title="Image" height="auto"></div></div></td></tr></table></td><td class="column column-2" width="50%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;padding-top:30px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class 
style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:14.399999999999999px;color:#9d9d9d;line-height:1.2"><p style="margin:0;font-size:14px;text-align:right;mso-line-height-alt:16.8px">Búscanos en <a href="{{ link.list.suscribe }}" target="_blank" rel="noopener" style="color: #ddac6e;">remaxnoa.com.ar</a>&nbsp;</p></div></div></td></tr></table><table class="button_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
style="text-align:right"><div class="alignment" align="right"><a href="tel:5493875969989" target="_blank"><!--[if mso]>
<v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word"  href="tel:5493875969989"  style="height:21px;width:77px;v-text-anchor:middle;" arcsize="20%" fill="false">
<v:stroke dashstyle="Solid" weight="0px" color="transparent"/>
<w:anchorlock/>
<v:textbox inset="0px,0px,0px,0px">
<center dir="false" style="color:#ffffff;font-family:sans-serif;font-size:14px">
<![endif]--><div style="background-color:transparent;border-bottom:0 solid transparent;border-left:0 solid transparent;border-radius:4px;border-right:0 solid transparent;border-top:0 solid transparent;color:#fff;display:inline-block;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;font-size:14px;font-weight:700;mso-border-alt:none;padding-bottom:0;padding-top:0;text-align:center;text-decoration:none;width:auto;word-break:keep-all">
<span style="word-break: break-word; padding-left: 0px; padding-right: 0px; font-size: 14px; display: inline-block; letter-spacing: normal;"><span style="word-break: break-word; line-height: 21px;">3875969989</span></span></div><!--[if mso]></center></v:textbox></v:roundrect><![endif]--></a></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-2" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0">
<table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%"><div class="alignment" align="center" style="line-height:10px"><div style="max-width:600px"><img src="https://easymailing-staging-bee.s3.amazonaws.com/images/admin/loveHome/lh-1.jpg" style="display:block;height:auto;border:0;width:100%" width="600" alt="Image" title="Image" height="auto"></div></div>
</td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-3" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td 
class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-top:25px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class 
style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:14.399999999999999px;color:#555;line-height:1.2"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px"><span style="word-break: break-word; font-size: 28px;">Hi, I´m a title</span></p></div></div></td></tr></table><table class="divider_block block-2" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr>
<td class="pad"><div class="alignment" align="center"><table border="0" cellpadding="0" cellspacing="0" role="presentation" width="10%" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="divider_inner" style="font-size:1px;line-height:1px;border-top:3px solid #c1a179"><span style="word-break: break-word;">&#8202;</span></td></tr></table></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-4" align="center" width="100%" border="0" 
cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:30px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class 
style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:14.399999999999999px;color:#555;line-height:1.2"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus</p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-5" align="center" width="100%" 
border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;padding-top:5px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%"><div class="alignment" align="center" style="line-height:10px"><div style="max-width:600px"><img 
src="https://easymailing-staging-bee.s3.amazonaws.com/images/admin/loveHome/lh-2.jpg" style="display:block;height:auto;border:0;width:100%" width="600" alt="Image" title="Image" height="auto"></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-6" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" 
border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-top:25px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="10" cellspacing="0" 
role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:14.399999999999999px;color:#555;line-height:1.2"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px">
<span style="word-break: break-word; color: #c1a179; font-size: 14px;"><strong><span style="word-break: break-word; font-size: 26px;">1.350.000 $</span></strong></span></p><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px"><span style="word-break: break-word; font-size: 18px;">2 Radford Avenue, Bondi Junction</span></p></div></div></td></tr></table><table class="divider_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-bottom:35px;padding-left:10px;padding-right:10px;padding-top:10px"><div class="alignment" align="center"><table border="0" cellpadding="0" cellspacing="0" role="presentation" width="10%" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="divider_inner" style="font-size:1px;line-height:1px;border-top:3px solid #c1a179"><span style="word-break: break-word;">&#8202;</span></td></tr></table></div></td></tr>
</table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-7" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#333;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" 
width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:30px;padding-top:5px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%"><div class="alignment" align="center" style="line-height:10px"><div style="max-width:276px"><img 
src="https://easymailing-staging-bee.s3.amazonaws.com/images/admin/loveHome/lh-plano.jpg" style="display:block;height:auto;border:0;width:100%" width="276" alt="Image" title="Image" height="auto"></div></div></td></tr></table></td><td class="column column-2" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;padding-top:5px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-1" 
width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%"><div class="alignment" align="center" style="line-height:10px"><div style="max-width:24px"><img src="https://easymailing-staging-bee.s3.amazonaws.com/images/admin/loveHome/ico-squares.png" style="display:block;height:auto;border:0;width:100%" width="24" alt="Image" title="Image" height="auto"></div></div></td></tr></table><table 
class="text_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-top:15px"><div style="font-family:sans-serif"><div class style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:14.399999999999999px;color:#555;line-height:1.2"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px">215 m2</p>
</div></div></td></tr></table><table class="divider_block block-3" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad"><div class="alignment" align="center"><table border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="divider_inner" style="font-size:1px;line-height:1px;border-top:1px solid #eaeaea">
<span style="word-break: break-word;">&#8202;</span></td></tr></table></div></td></tr></table><table class="image_block block-4" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-top:5px;width:100%"><div class="alignment" align="center" style="line-height:10px"><div style="max-width:24px"><img src="https://easymailing-staging-bee.s3.amazonaws.com/images/admin/loveHome/ico-bedroom.png" 
style="display:block;height:auto;border:0;width:100%" width="24" alt="Image" title="Image" height="auto"></div></div></td></tr></table><table class="text_block block-5" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-top:15px"><div style="font-family:sans-serif"><div class 
style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:14.399999999999999px;color:#555;line-height:1.2"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px">3 Bedrooms</p></div></div></td></tr></table><table class="divider_block block-6" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad"><div class="alignment" align="center"><table 
border="0" cellpadding="0" cellspacing="0" role="presentation" width="100%" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="divider_inner" style="font-size:1px;line-height:1px;border-top:1px solid #eaeaea"><span style="word-break: break-word;">&#8202;</span></td></tr></table></div></td></tr></table><table class="image_block block-7" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
style="padding-top:5px;width:100%"><div class="alignment" align="center" style="line-height:10px"><div style="max-width:24px"><img src="https://easymailing-staging-bee.s3.amazonaws.com/images/admin/loveHome/ico-bathroom.png" style="display:block;height:auto;border:0;width:100%" width="24" alt="Image" title="Image" height="auto"></div></div></td></tr></table><table class="text_block block-8" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:20px;padding-top:15px"><div style="font-family:sans-serif"><div class style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:14.399999999999999px;color:#555;line-height:1.2"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px">2 Bathrooms</p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody>
</table><table class="row row-8" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#6a5e4f;color:#333;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="50%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#6a5e4f;padding-bottom:5px;padding-left:5px;padding-right:5px;padding-top:5px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="40" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class 
style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:14.399999999999999px;color:#f6f6f6;line-height:1.2"><p style="margin:0;font-size:14px;mso-line-height-alt:16.8px"><span style="word-break: break-word; font-size: 26px;">Hi, I´m a title</span></p><p style="margin:0;font-size:14px;mso-line-height-alt:16.8px">&nbsp;<br></p><p style="margin:0;font-size:14px;mso-line-height-alt:16.8px"><strong>Lorem ipsum dolor sit amet, consectetuer adipiscing</strong>
</p><p style="margin:0;font-size:14px;mso-line-height-alt:16.8px">&nbsp;<br></p><p style="margin:0;font-size:14px;mso-line-height-alt:16.8px">Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam .</p></div></div></td></tr></table><table class="button_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" 
style="padding-bottom:30px;padding-left:40px;padding-right:10px;padding-top:10px;text-align:left"><div class="alignment" align="left"><!--[if mso]>
<v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word"   style="height:33px;width:112px;v-text-anchor:middle;" arcsize="0%" fill="false">
<v:stroke dashstyle="Solid" weight="1px" color="#FFFFFF"/>
<w:anchorlock/>
<v:textbox inset="0px,0px,0px,0px">
<center dir="false" style="color:#ffffff;font-family:sans-serif;font-size:16px">
<![endif]--><div style="background-color:transparent;border-bottom:1px solid #fff;border-left:1px solid #fff;border-radius:0;border-right:1px solid #fff;border-top:1px solid #fff;color:#fff;display:inline-block;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;font-size:16px;font-weight:undefined;mso-border-alt:none;padding-bottom:0;padding-top:0;text-align:center;text-decoration:none;width:auto;word-break:keep-all">
<span style="word-break: break-word; padding-left: 15px; padding-right: 15px; font-size: 16px; display: inline-block; letter-spacing: normal;"><span style="word-break: break-word; line-height: 32px;">Learn More</span></span></div><!--[if mso]></center></v:textbox></v:roundrect><![endif]--></div></td></tr></table></td><td class="column column-2" width="50%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#6a5e4f;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px"><div style="max-width:300px">
<img src="https://easymailing-staging-bee.s3.amazonaws.com/images/admin/loveHome/lh-3.jpg" style="display:block;height:auto;border:0;width:100%" width="300" alt="Image" title="Image" height="auto"></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-9" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" 
align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-top:25px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="10" 
cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:14.399999999999999px;color:#555;line-height:1.2"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px"><span style="word-break: break-word; font-size: 16px; color: #9d9d9d;">Our Blog</span></p><p 
style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px"><span style="word-break: break-word; font-size: 28px;">Last Minute</span></p></div></div></td></tr></table><table class="divider_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-bottom:30px;padding-left:10px;padding-right:10px;padding-top:10px"><div class="alignment" align="center"><table 
border="0" cellpadding="0" cellspacing="0" role="presentation" width="10%" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="divider_inner" style="font-size:1px;line-height:1px;border-top:3px solid #c1a179"><span style="word-break: break-word;">&#8202;</span></td></tr></table></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-10" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;background-color:#fff;color:#333;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="50%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div class="alignment" align="center" style="line-height:10px"><div style="max-width:276px"><img 
src="https://easymailing-staging-bee.s3.amazonaws.com/images/admin/loveHome/lh-4.jpg" style="display:block;height:auto;border:0;width:100%" width="276" alt="Image" title="Image" height="auto"></div></div></td></tr></table><table class="text_block block-2" width="100%" border="0" cellpadding="35" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad"><div style="font-family:sans-serif"><div class 
style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:18px;color:#6e6e6e;line-height:1.5"><p style="margin:0;font-size:14px;mso-line-height-alt:27px"><span style="word-break: break-word; font-size: 18px; color: #40454b;"><strong>Lorem ipsum dolor sit amet, consectetuer adipiscing</strong></span></p><p style="margin:0;font-size:14px;mso-line-height-alt:21px">&nbsp;<br></p><p style="margin:0;font-size:14px;mso-line-height-alt:21px">
Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam</p><p style="margin:0;font-size:14px;mso-line-height-alt:21px">&nbsp;<br></p><p style="margin:0;font-size:14px;mso-line-height-alt:21px"><a style="text-decoration: none; color: #ddac6e;" href="#" target="_blank" rel="noopener">Read more &gt;</a></p><p style="margin:0;font-size:14px;mso-line-height-alt:21px">
&nbsp;<br></p></div></div></td></tr></table></td><td class="column column-2" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:5px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="image_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%;padding-right:0;padding-left:0"><div 
class="alignment" align="center" style="line-height:10px"><div style="max-width:276px"><img src="https://easymailing-staging-bee.s3.amazonaws.com/images/admin/loveHome/lh-5.jpg" style="display:block;height:auto;border:0;width:100%" width="276" alt="Image" title="Image" height="auto"></div></div></td></tr></table><table class="text_block block-2" width="100%" border="0" cellpadding="35" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td
 class="pad"><div style="font-family:sans-serif"><div class style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:18px;color:#6e6e6e;line-height:1.5"><p style="margin:0;font-size:14px;mso-line-height-alt:27px"><span style="word-break: break-word; font-size: 18px; color: #40454b;"><strong>Lorem ipsum dolor sit amet, consectetuer adipiscing</strong></span></p><p style="margin:0;font-size:14px;mso-line-height-alt:21px">&nbsp;<br></p><p 
style="margin:0;font-size:14px;mso-line-height-alt:21px">Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam</p><p style="margin:0;font-size:14px;mso-line-height-alt:21px">&nbsp;<br></p><p style="margin:0;font-size:14px;mso-line-height-alt:21px"><a style="text-decoration: none; color: #ddac6e;" href="#" target="_blank" rel="noopener">Read more &gt;</a></p><p 
style="margin:0;font-size:14px;mso-line-height-alt:21px">&nbsp;<br></p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-11" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;background-color:#2c3239;color:#333;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="50%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#6a5e4f;padding-bottom:12px;padding-left:10px;padding-right:10px;padding-top:10px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="0" 
cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-left:35px;padding-right:35px;padding-top:35px"><div style="font-family:sans-serif"><div class style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:14.399999999999999px;color:#f6f6f6;line-height:1.2"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px">
<span style="word-break: break-word; font-size: 22px;">I´m your agent</span></p><p style="margin:0;mso-line-height-alt:26.4px"><br></p></div></div></td></tr></table><table class="image_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="width:100%"><div class="alignment" align="center" style="line-height:10px"><div style="max-width:92px"><img 
src="https://easymailing-staging-bee.s3.amazonaws.com/images/admin/loveHome/perfil.png" style="display:block;height:auto;border:0;width:100%" width="92" alt="Image" title="Image" height="auto"></div></div></td></tr></table><table class="text_block block-3" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" 
style="padding-bottom:25px;padding-left:10px;padding-right:10px;padding-top:15px"><div style="font-family:sans-serif"><div class style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:14.399999999999999px;color:#fff;line-height:1.2"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px"><strong>John Doe</strong></p><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px">+ 34 555 55 87</p><p 
style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px"><a style="text-decoration: underline; color: #ddac6e;" title="j.doe@company.com" href="mailto:j.doe@company.com">j.doe@company.com</a></p></div></div></td></tr></table></td><td class="column column-2" width="50%" 
style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;background-color:#2c3239;padding-bottom:10px;padding-left:10px;padding-right:10px;padding-top:10px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-top:35px"><div 
style="font-family:sans-serif"><div class style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:14.399999999999999px;color:#f6f6f6;line-height:1.2"><p style="margin:0;font-size:14px;text-align:center;mso-line-height-alt:16.8px"><span style="word-break: break-word; font-size: 22px;"><span id="mce_1_start" style="word-break: break-word; overflow: hidden; font-size: 22px;">&nbsp;</span>Síguenos</span></p></div></div></td></tr></table><table 
class="social_block block-2" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tr><td class="pad" style="padding-bottom:35px;padding-top:15px;text-align:center;padding-right:0;padding-left:0"><div class="alignment" align="center"><table class="social-table" width="111px" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0;display:inline-block"><tr><td 
style="padding:0 5px 0 0"><a href="https://www.facebook.com/" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-circle-white/facebook@2x.png" width="32" height="auto" alt="Facebook" title="Facebook" style="display:block;height:auto;border:0"></a></td><td style="padding:0 5px 0 0"><a href="https://twitter.com/" target="_blank"><img 
src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-circle-white/twitter@2x.png" width="32" height="auto" alt="Twitter" title="Twitter" style="display:block;height:auto;border:0"></a></td><td style="padding:0 5px 0 0"><a href="https://plus.google.com/" target="_blank"><img src="https://app-rsrc.getbee.io/public/resources/social-networks-icon-sets/t-circle-white/googleplus@2x.png" width="32" height="auto" alt="Google+" title="Google+" 
style="display:block;height:auto;border:0"></a></td></tr></table></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table><table class="row row-12" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace:0;mso-table-rspace:0"><tbody><tr><td><table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;color:#000;width:600px;margin:0 auto" width="600"><tbody><tr><td class="column column-1" width="100%" style="mso-table-lspace:0;mso-table-rspace:0;font-weight:400;text-align:left;padding-bottom:55px;padding-top:25px;vertical-align:top;border-top:0;border-right:0;border-bottom:0;border-left:0"><table class="text_block block-1" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" 
style="mso-table-lspace:0;mso-table-rspace:0;word-break:break-word"><tr><td class="pad" style="padding-bottom:30px;padding-left:10px;padding-right:10px;padding-top:10px"><div style="font-family:sans-serif"><div class style="font-size:12px;font-family:Arial,Helvetica Neue,Helvetica,sans-serif;mso-line-height-alt:14.399999999999999px;color:#9d9d9d;line-height:1.2"><p style="margin:0;font-size:12px;text-align:center;mso-line-height-alt:14.399999999999999px">
Este email ha sido enviado a {{ text.list.suscriber.email }}&nbsp;<br><a href="{{ link.campaign.unsuscribe }}" target="_blank" rel="noopener" style="color: #ddac6e;">Darme de Baja</a>&nbsp; |&nbsp;<a href="{{ link.list.update_profile }}" target="_blank" rel="noopener" style="color: #ddac6e;">Editar preferencias de la suscripción</a>&nbsp;</p><p style="margin:0;font-size:12px;text-align:center;mso-line-height-alt:14.399999999999999px">&nbsp;</p><p style="margin:0;font-size:12px;text-align:center;mso-line-height-alt:14.399999999999999px"><strong>{{ text.list.company.name }}&nbsp;</strong><br>{{ text.list.company.address }}&nbsp;<br>
{{ text.list.company.postal_code }}. {{ text.list.company.city }}. {{ text.list.company.province }}. {{ text.list.company.country }}</p></div></div></td></tr></table></td></tr></tbody></table></td></tr></tbody></table></td></tr></tbody></table><!-- End --></body></html>
          `,
  };

  return await transporter.sendMail(mailOption);
};
